version: "3.5"

services:
  api:
    image: server-health-monitor_api
    container_name: api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    restart: always
    volumes:
      - ${CERT_DIR}:${CERT_DIR}
    depends_on:
      - "database"
  database:
    image: "mongo"
    container_name: database
    ports:
      - "27017-27019:27017-27019"
    env_file: .env
    restart: always
