version: "3.5"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: cmd/api/Dockerfile
    ports:
      - "${API_PORT}:3000"
    env_file: .env
    restart: always
    volumes:
      - ${CERT_DIR}:${CERT_DIR}
    depends_on:
      - "database"
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:4000"
    env_file: .env
    restart: always
  database:
    image: "mongo"
    container_name: database
    ports:
      - "27017-27019:27017-27019"
    env_file: .env
    restart: always
