version: "3.5"

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: cmd/api/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    restart: always
    volumes:
      - ${CERT_DIR}:${CERT_DIR}
